web:
  build: www/
  dockerfile: Dockerfile
  ports:
    - "80:80"
  links:
    - node
node:
  build: node/
  dockerfile: Dockerfile
  ports:
    - "3000:3000"
  links:
    - mongo
mongo:
  build: mongo/
  dockerfile: Dockerfile
  ports:
    - "27017:27017"
